# Generated by Django 4.1.7 on 2023-04-21 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_comp', models.CharField(db_index=True, max_length=50, verbose_name='тип компонента')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория компонента',
                'verbose_name_plural': 'Категории компонентов',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Components',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='фото')),
                ('description', models.TextField(max_length=1000, verbose_name='описание')),
                ('tel', models.CharField(max_length=10, verbose_name='телефон')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('time_upgrate', models.DateTimeField(auto_now=True, verbose_name='последнее редактирование')),
                ('is_publishes', models.BooleanField(default=True, verbose_name='статус пупликации')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='components.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'Компьютерные комплектующие',
                'verbose_name_plural': 'Компьютерные комплектующие',
                'ordering': ['-time_create', 'name'],
            },
        ),
    ]
