# Generated by Django 4.1.7 on 2023-04-20 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_category_components_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Категория компонента', 'verbose_name_plural': 'Категории компонентов'},
        ),
        migrations.AlterModelOptions(
            name='components',
            options={'ordering': ['-time_create', 'name'], 'verbose_name': 'Компьютерные комплектующие', 'verbose_name_plural': 'Компьютерные комплектующие'},
        ),
        migrations.AlterField(
            model_name='category',
            name='type_comp',
            field=models.CharField(db_index=True, max_length=50, verbose_name='тип компонента'),
        ),
        migrations.AlterField(
            model_name='components',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='components.category', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='components',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='components',
            name='is_publishes',
            field=models.BooleanField(default=True, verbose_name='статус пупликации'),
        ),
        migrations.AlterField(
            model_name='components',
            name='name',
            field=models.CharField(max_length=100, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='components',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='components',
            name='tel',
            field=models.CharField(max_length=10, verbose_name='телефон'),
        ),
        migrations.AlterField(
            model_name='components',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='время создания'),
        ),
        migrations.AlterField(
            model_name='components',
            name='time_upgrate',
            field=models.DateTimeField(auto_now=True, verbose_name='последнее редактирование'),
        ),
    ]
